package MusicMain;

import java.io.File;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import java.awt.EventQueue;


import sun.audio.*;

public class MusicPlayerGui {

    private JFrame frame;
//    AudioStream as;
    private JButton startButton;
    private JTextField pathField;
    private JButton openButton;




    public static void main(String[] args) {

//        new MusicPlayerGui().createGui();

        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

                    MusicPlayerGui window = new MusicPlayerGui();
                    window.frame.setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });

    }

    public MusicPlayerGui() {
        initialize();
        startButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //play audio
            }
        });
        pathField.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
    }

    private void initialize() {
        frame = new JFrame();
        frame.setBounds(100, 100, 450, 300);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setLocationRelativeTo(null);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        startButton = new JButton();
        startButton.setText("Start");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(startButton, gbc);
        pathField = new JTextField();
        pathField.setEditable(false);
        pathField.setForeground(new Color(-7237231));
        pathField.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(pathField, gbc);
        openButton = new JButton();
        openButton.setText("Open");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(openButton, gbc);
    }

//    public void createGui(){
//        JFrame frame = new JFrame("Music Player");
//        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        frame.setLayout(new GridLayout(1,3,5,5));
//        frame.add(play);
//        frame.add(stop);
//        frame.add(pause);
//        frame.pack();
//        frame.setVisible(true);
//
//        play.addActionListener(this);
//        stop.addActionListener(this);
//        pause.addActionListener(this);
//
//        try{
//            as = new AudioStream(this.getClass().getResourceAsStream("/BofYou.mp3"));
//        } catch (IOException e) {
//            System.out.println("Error with playing sound.");
//            e.printStackTrace();
//        }
//    }

//    public void actionPerformed(ActionEvent arg0){
//        if(arg0.getSource() == play){
//            AudioPlayer.player.start(as);
//        }
//        else if(arg0.getSource() == stop){
//            AudioPlayer.player.stop(as);
//            try{
//                as = new AudioStream(this.getClass().getResourceAsStream("/BofYou.mp3"));
//            } catch (IOException e) {
//                System.out.println("Error with playing sound. (stop) ");
//                e.printStackTrace();
//            }
//        }
//        else {
//            AudioPlayer.player.stop(as);
//        }
//    }
}

